### ISSUE TITLE
Does not work on IE

### ISSUE THREAD

**Issue by nikoloza** [Epimodev/parcel-plugin-svg-sprite#14]
It can't really create `<use>` tag inside `<svg>` element

This might help https://github.com/sinnerschrader/svg-use-it

**Comment by Epimodev** [comment]
Hello

Thanks to report this issue, I never try this on IE.
I don’t think `svg-use-it` will solve this issue because it’s a polyfill to use ˋ<use>ˋ element with external ressource. Whereas with this plugin, all svg are already loaded in the DOM.

Can you send an example please ? A codesandbox will be perfect, or just the code which create ˋsvg` with ˋuseˋ element should be enough. 


ℹ️ there is also https://github.com/jonathantneal/svg4everybody to polyfill external svg reference in ˋ<use>ˋ
