### ISSUE TITLE
Creates a <svg#hashname>.js and .js.map file for each SVG referenced.

### ISSUE THREAD

**Issue by brendanheyu** [Epimodev/parcel-plugin-svg-sprite#34]
Hi there! Just found your plugin for Parcel2 today - what a life saver! Thanks!!! Is it me or is Parcel2 forgetting it's zero-config roots? :)

I'm finding that when I use parcel both in _dev_ and in _build_ that there seems to be a bunch of files generated. These files are files with the same name as the SVG files - but with js and map extensions.

The js file contains no SVG, and just a reference to the map file. The map file doesn't contain much to report.

To clarify: If I have icons A, B, and C in SVG format - where my code may only reference A and B icons - my generated output will contain:
```
index.html
index.hash.js
A.hash.js
A.hash.js.map
B.hash.js
B.hash.js.map
```
The index.html still contains the SVG inline with the symbols as expected. 

The output still references correctly:
```
<svg viewBox="0 0 16 16" width="24">
  <use viewBox="0 0 16 16" width="24" xlink:href="#0c01f9b125241227">
</use></svg>
```

I just don't understand what I have misconfigured in order to be generating these extra files during running "parcel" or a "parcel build".

Any pointers?

**Comment by Epimodev** [comment]
Hi @brendanheyu !

Thanks a lot for your feedback, I appreciate it a lot.  
I don't use parcel anymore for almost 2 years because I prefer [vite](https://vitejs.dev/). But yes if you want to use some plugins you must create a config file.

About `.js` and `.js.map` I don't remember exactly why there are created but I didn't find a way to not generate them. This isn't a misconfiguration from you're side and you can just ignore them because they don't impact the bundled index.html file.

Sorry for the lack of detail in this response, as I said, I no longer use Parcel and upgraded this plugin to Parcel v2 just for the community.

**Comment by brendanheyu** [comment]
Hi @Epimodev :)

Hey - no problem! I would love to see if Vite could to do the work I need - Parcel2 is making life difficult for me right now! Apparently now Parcel2 has an opinion about multiple .env.* files - I can't cover 5 environments (local/dev/sit/uat/prod) - I seem to be limited to 3? so painful :)

Vite seems a little complex too. Not as big a community and a few less plugins :) . Not sure Handlebars gets the love I need.

Merci beaucoup!

**Comment by Epimodev** [comment]
Hello!

I never tried to port this plugin to Vite because I changed my workflow to use svg icons last year.

About environment files limitation I don't know. I always used only 1 `.env` file for my local env, for other environments I set variables in the service I use to deploy my apps (Vercel or Gitlab depending on the project).

Since I switch to Vite I didn't have the feeling this is more complex than Parcel. But this is just my experience, it might be more complex for some cases.  
For Handlbars I found this plugin: [vite-plugin-handlebars](https://github.com/alexlafroscia/vite-plugin-handlebars), I didn't try it but it seems nice.

You're welcome!
