### ISSUE TITLE
Generating a lot of js

### ISSUE THREAD

**Issue by dreit-p** [Epimodev/parcel-plugin-svg-sprite#9]
This plugin connects content of every used svg in every html and also generates almost identical js files for every svg image and also creates links in every html to the scripts, which will be downloaded. 
Then for what is it, if i can just download images instead of such js scripts?
What is the advantage of this solution?

The built html:
[https://pastebin.com/F1PwhCKU](https://pastebin.com/F1PwhCKU)

Example of generated js:
[https://pastebin.com/3bKb8JyZ](https://pastebin.com/3bKb8JyZ)

Maybe did I do something wrong?

**Comment by Epimodev** [comment]
Hello @dreit-p 

Sorry for this late answer.

Thanks for this issue, this happen only when svg are imported from html file.
Js files related to imported svg shouldn't be created and script tags shouldn't be added in built html.

So this is a problem coming from parcel and this plugin.

I'm not sure that parcel plugin system give enough flexibility to avoid this behavior but I'll try to find a solution.

**Comment by Epimodev** [comment]
Hi !

I've just publish v1.4.1 which solve partially your problem.

With this update js files coming from svg import will not be downloaded anymore.

But those files are always generated, I didn't find a way to avoid this behavior.
If you want to have a clean `dist` folder, you can delete those files because there aren't use.

In my opinion in this issue, the main problem was the fact those js files were downloaded whereas they are useless. So I consider this issue resolved even if the solution isn't perfect.
